spring:
  application:
    name: springboottutorial
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/amazon_example?useSSL=false
    password: rootpass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
